# name: terraform infra and deploy

# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: checkout code
#         uses: actions/checkout@v6

#       - name: Azure Login
#         uses: azure/login@v1
#         with:
#           creds: ${{ secrets.AZURE_SECRETS }}

#       - name: setup terraform
#         uses: hashicorp/setup-terraform@v3

#       - name: terraform init
#         working-directory: terraform
#         run: terraform init

#       - name: terraform apply
#         working-directory: terraform
#         run: terraform apply -auto-approve
#       - name: Setup .NET
#         uses: actions/setup-dotnet@v5
#         with:
#           dotnet-version: '10.0.x'

#       - name: Restore dependencies
#         run: dotnet restore

#       - name: Build application
#         run: dotnet build --no-restore
         
#       - name: publish application
#         run: dotnet publish HDFCGITHUBproject.csproj -c Release -o publish

#       - name: Deploy to Azure Web App
#         uses: azure/webapps-deploy@v2
#         with:
#           app-name: hdfc-web-app098
#           package: publish  


name: Terraform Infra and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --no-restore --configuration Release

      - name: Publish application
        run: dotnet publish HDFCGITHUBproject.csproj --configuration Release --output ./publish
      - name: show the repo  struture
        run: ls -R

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_SECRETS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # - name: Terraform Init
      #   working-directory: terraform
      #   run: terraform init

      # - name: Terraform Validate
      #   working-directory: terraform
      #   run: terraform validate

      # - name: Terraform Plan
      #   working-directory: terraform
      #   run: terraform plan

      # - name: Terraform Apply
      #   working-directory: terraform
      #   run: terraform apply -auto-approve

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: hdfc-web-app098
          package: ./publish
